import LayOutHtml from "@/app/LayoutHtml";
import Context from "@/app/context";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Money Management App",
  description: "Generated by Money Management App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Context>
      <LayOutHtml>{children}</LayOutHtml>
    </Context>
  );
}
