import { montserrat, openSans, roboto } from "@/app/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${openSans.variable} ${roboto.variable} `}
    >
      <body className="bg-slate-50 dark:bg-slate-800">{children}</body>
    </html>
  );
}
