import Context, { MyContext } from "@/app/context";
import { montserrat, openSans, roboto } from "@/app/utils/fonts";
import type { Metadata } from "next";
import React, { useContext } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Money Management App",
  description: "Generated by Money Management App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const context = useContext(MyContext);

  if (!context) {
    throw new Error("MyContext must be used within a MyProvider");
  }

  const { darkMode } = context;

  return (
    <Context>
      <html
        lang="en"
        className={`${montserrat.variable} ${openSans.variable} ${
          roboto.variable
        } ${darkMode ? "dark" : ""} `}
      >
        <body className="bg-slate-50 dark:bg-slate-800 text-slate-800 dark:text-slate-50">
          {children}
        </body>
      </html>
    </Context>
  );
}
